stages:
- build
- test
- coverage
- deploy

before_script:
  - pip install -r requirements.txt

test:
 image:
  name: "python:3.6"
 stage: test
 script:
   - pytest --cov=. tests/*
   - coverage report -m
   - coverage-badge
 coverage: '/TOTAL.+ ([0-9]{1,3}%)/'